/*
 * Copyright 2026 Olav Gjerde
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.intellistream.threadorbit.web.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * @param body the message text.
 * @param clientId opaque correlation token generated by the sender, echoed back on the resulting
 *   {@link MessageEvent}. It lets a client render its own message immediately as "sending" and
 *   then match the broadcast that confirms it, instead of guessing by body text — which breaks the
 *   moment someone sends the same line twice. Optional: clients that don't do optimistic rendering
 *   omit it, and the field is elided from the broadcast.
 */
public record SendMessageRequest(
        @NotBlank @Size(max = 8000) String body,
        @Size(max = 64) String clientId
) {
    /** A send with no correlation token — the shape every non-optimistic caller wants. */
    public SendMessageRequest(String body) {
        this(body, null);
    }
}
