/*
 * Copyright 2026 Olav Gjerde
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ai.intellistream.threadorbit.service;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Reads the real asset-bundles.properties generated by assets.gradle (buildAssets runs before
 * processResources, so it is always on the test classpath). The hash in the prod URL changes
 * per build, so assertions match its shape, not its value.
 */
class AssetServiceTest {

    @Test
    void productionReturnsTheSingleHashVersionedBundle() {
        List<String> urls = new AssetService(false).urls("chat");

        assertEquals(1, urls.size());
        assertTrue(urls.getFirst().matches("/js/chat\\.bundle\\.min\\.js\\?v=[0-9a-f]{10}"), urls.toString());
    }

    @Test
    void cssBundleIsHashVersionedToo() {
        List<String> urls = new AssetService(false).urls("app");

        assertEquals(1, urls.size());
        assertTrue(urls.getFirst().matches("/css/app\\.bundle\\.min\\.css\\?v=[0-9a-f]{10}"), urls.toString());
    }

    @Test
    void devReturnsManifestSourcesInOrder() {
        List<String> sources = new AssetService(true).urls("chat");

        // theme-loader must stay first (it ran before the other scripts as a standalone tag);
        // the rest mirror the manifest's declared order.
        assertEquals("/js/theme-loader.js", sources.getFirst());
        assertEquals(8, sources.size());
        assertTrue(sources.contains("/js/chat-kit.js"), sources.toString());
        assertTrue(sources.stream().allMatch(s -> s.startsWith("/js/")), sources.toString());
    }

    @Test
    void unknownBundleThrows() {
        assertThrows(IllegalArgumentException.class, () -> new AssetService(false).urls("does-not-exist"));
    }
}
