/*
 * Copyright 2026 IntelliStream AS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.intellistream.chat.domain;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Arrays;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link Channel} must stay immutable after creation, because a cached copy of one is used to make
 * an authorization decision.
 *
 * <p>{@code ChannelAccessCache} serves cached {@code Channel} instances to STOMP SUBSCRIBE
 * authorization, which calls {@code ChannelService.requireMember} — and that short-circuits to
 * "allowed" for a PUBLIC channel. So a mutable {@code type} means a PUBLIC→PRIVATE change leaves a
 * stale cached copy authorizing non-members to subscribe to a channel that is no longer public,
 * for as long as the cache TTL.
 *
 * <p>This is a reflection test rather than a code-review convention for a specific reason: the
 * setters it guards against were generated by Lombok's {@code @Setter}, which means they do not
 * appear in the source at all. Grepping for {@code void set} finds nothing, which is exactly how
 * the cache came to be documented as safe on an invariant that was false. Reflection sees the
 * compiled class, so it sees what a grep cannot.
 *
 * <p>If you need to change a channel, add a method on {@code ChannelService} that makes the change
 * <em>and</em> calls {@code ChannelAccessCache.evictChannel}, then allow it here by name.
 */
class ChannelImmutabilityTest {

    @Test
    void channelExposesNoPublicSetters() {
        var setters = Arrays.stream(Channel.class.getMethods())
                .filter(m -> m.getName().startsWith("set"))
                .filter(m -> Modifier.isPublic(m.getModifiers()))
                .filter(m -> m.getDeclaringClass().equals(Channel.class))
                .map(Method::getName)
                .sorted()
                .toList();

        assertThat(setters)
                .describedAs("Channel must stay immutable — a cached copy authorizes STOMP "
                        + "SUBSCRIBE, and requireMember short-circuits to allowed for PUBLIC "
                        + "channels. Route changes through ChannelService and evict the cache.")
                .isEmpty();
    }

    @Test
    void theTypeFieldInParticularHasNoMutator() {
        // Called out separately from the blanket check above: name and description going stale is
        // cosmetic, type going stale is an authorization bypass. If the general assertion is ever
        // relaxed, this one must not be.
        var typeMutators = Arrays.stream(Channel.class.getMethods())
                .map(Method::getName)
                .filter(n -> n.equalsIgnoreCase("setType"))
                .toList();

        assertThat(typeMutators)
                .describedAs("Channel.type must not be mutable: PUBLIC->PRIVATE with a cached "
                        + "PUBLIC copy in front of requireMember lets a non-member subscribe to a "
                        + "now-private channel until the ChannelAccessCache TTL expires")
                .isEmpty();
    }
}
