-- Saved messages: a private, per-user, cross-room queue of things to come back to. The analogue of
-- Slack's "Later" and Mattermost's saved posts.
--
-- Pins are named in this migration's filename and get no table in it, deliberately. V1 already gave
-- `messages` its pinned_at / pinned_by columns and a partial index over them, and a pin is exactly
-- one fact about one message — a second home for it would be a second source of truth for something
-- that has never needed one. Saves are not like that: they are per-user rows about somebody else's
-- message, and they span both message tables, so they need one.
--
-- One table for both kinds rather than two parallel ones. The list this backs is "everything I
-- saved, newest first", which is one ordering across channels and DMs; two tables would mean two
-- queries and a merge in Java, with the paging done by hand. The exclusive-or check is what keeps
-- the shape honest: exactly one of the two targets is set, always, enforced by the database rather
-- than by whichever service happens to insert the row.

create table message_saves (
    id                      bigint      generated by default as identity primary key,
    user_id                 bigint      not null references users(id) on delete cascade,
    message_id              bigint      references messages(id) on delete cascade,
    conversation_message_id bigint      references conversation_messages(id) on delete cascade,
    created_at              timestamptz not null default now(),
    constraint ck_message_saves_one_target check (
        (message_id is not null) <> (conversation_message_id is not null))
);

-- on delete cascade on both targets, which is the whole answer to "what happens to a save when the
-- message goes". A deleted message, a purged one, and every message in a destroyed channel all take
-- their saves with them, in the database, without any service remembering to. The user_id cascade
-- is the same answer for a deleted account.

-- Partial uniques rather than one composite: saving the same message twice is one save, and NULLs
-- do not collide in a plain unique index, so (user_id, message_id) alone would let a user
-- accumulate unlimited duplicate rows for their conversation saves and vice versa.
create unique index ux_message_saves_message on message_saves(user_id, message_id)
    where message_id is not null;
create unique index ux_message_saves_conv_message on message_saves(user_id, conversation_message_id)
    where conversation_message_id is not null;

-- The list query: one user's saves, newest first.
create index ix_message_saves_user_created on message_saves(user_id, created_at desc);
-- The feed query: which of this channel's messages has this user saved. Answered from the index
-- alone for the common case of a handful of saves.
create index ix_message_saves_message on message_saves(message_id) where message_id is not null;
