-- Link previews: the card under a message that contains a URL — title, description, site name
-- and, when the page offers one, a picture.
--
-- One row per URL, not per message. A preview is a fact about the page, not about who pasted it,
-- so the tenth person to paste the same article costs no fetch, and a message never carries a
-- preview column: which URL a message shows is derived from its body at read time and looked up
-- here. That keeps `messages` and the write-behind INSERT exactly as they were, and it is what
-- makes an edit that swaps the link Just Work — the next read looks up a different URL.
--
-- The image is not the page's URL. It is a copy, fetched once by the server under the same
-- guard as the page and stored under ichat.link-previews.dir like an avatar; image_key is its
-- filename there and the only thing the client is given. Hotlinking would leak every reader's
-- address to every site anyone ever linked, and the CSP's img-src forbids it anyway.
--
-- status is FETCHED / EMPTY / FAILED. EMPTY is a page that answered but had nothing worth a card
-- (no title at all); FAILED is one that did not answer, answered with something that was not
-- HTML, or was refused by the SSRF guard. Both are kept as negative cache: fetched_at says when,
-- and the service decides when a sighting is old enough to try again.
--
-- last_seen_at is bumped when a message posts the URL, never on read, so a busy channel scrolling
-- old history is not a write per message; retention purges rows nobody has posted in a long time
-- (and their image files) — an old message then simply shows the bare link again.

create table link_previews (
    id                 bigint       generated by default as identity primary key,
    url_hash           varchar(64)  not null,
    url                text         not null,
    status             varchar(16)  not null,
    title              varchar(300),
    description        varchar(600),
    site_name          varchar(120),
    image_key          varchar(64),
    image_content_type varchar(80),
    fetched_at         timestamptz  not null,
    last_seen_at       timestamptz  not null,
    constraint uk_link_previews_url_hash unique (url_hash),
    constraint link_previews_status_chk check (status in ('FETCHED', 'EMPTY', 'FAILED'))
);

create index ix_link_previews_last_seen on link_previews (last_seen_at);
