-- One-time secrets: a password or token handed to someone through a link that opens exactly once.
--
-- The server never sees the secret. The browser that creates one encrypts it with a random key
-- (AES-256-GCM, via Web Crypto) and puts the key in the link's #fragment, which a browser never
-- sends to a server. What arrives here is ciphertext (payload) and a hash of a value derived from
-- that key (verifier_hash): opening the secret, or even asking whether it still exists, requires
-- presenting the derived value, so whoever holds only the id — an access log, the link-preview
-- fetcher, a link whose fragment was stripped, or a read-only copy of this table — can neither
-- read nor burn it.
--
-- Lifecycle. A row is WAITING while payload is present and expires_at is in the future. It ends in
-- exactly one of three ways, and payload is set to null at that moment:
--   opened   opened_at set, plus who opened it;
--   revoked  revoked_at set by the creator;
--   expired  expires_at passed; the sweeper nulls the payload, and the open path refuses it before
--            the sweeper gets there, so an unswept row is never served.
-- Nulling a bytea is a logical wipe: the old tuple lives on in dead tuples, WAL and backups until
-- vacuum and backup rotation. It is ciphertext without its key either way.
--
-- label is a note to the creator ("prod DB for bob"), stored in plain text and shown to nobody else.
-- The page that collects it says so.
--
-- Who opened it. A signed-in opener is recorded by id and by a copy of their handle taken at open
-- time; the copy is what keeps "opened by @bob" true after bob's account is deleted, which would
-- otherwise null the foreign key and make the open look anonymous. An opener without an account
-- (audience ANYONE) is recorded by IP address as the proxy reported it and a short browser summary
-- ("Firefox on Windows") — never the raw User-Agent. That is personal data about someone outside
-- the workspace: it is shown only to the creator, and it is deleted with the row once
-- ichat.secrets.retention has passed since the secret ended.
--
-- app_settings.allow_public_secrets is the workspace switch for audience ANYONE. Default true;
-- when an admin turns it off, creating one is refused and an existing one requires sign-in to open.

create table secret_shares (
    id              bigint       generated by default as identity primary key,
    public_id       varchar(22)  not null,
    creator_id      bigint       not null references users(id) on delete cascade,
    label           varchar(80),
    payload         bytea,
    verifier_hash   bytea        not null,
    audience        varchar(16)  not null,
    created_at      timestamptz  not null default now(),
    expires_at      timestamptz  not null,
    opened_at       timestamptz,
    opened_by_id    bigint       references users(id) on delete set null,
    opened_by_name  varchar(100),
    opened_ip       varchar(45),
    opened_client   varchar(64),
    revoked_at      timestamptz,
    constraint uk_secret_shares_public_id unique (public_id),
    constraint ck_secret_shares_audience check (audience in ('SIGNED_IN', 'ANYONE')),
    constraint ck_secret_shares_verifier_len check (octet_length(verifier_hash) = 32),
    constraint ck_secret_shares_expiry check (expires_at > created_at),
    -- An ended secret holds no ciphertext.
    constraint ck_secret_shares_payload_gone check (payload is null or (opened_at is null and revoked_at is null)),
    -- Opened or revoked, never both.
    constraint ck_secret_shares_one_ending check (opened_at is null or revoked_at is null),
    -- Opener details only exist for an opened secret.
    constraint ck_secret_shares_opener check (opened_at is not null
        or (opened_by_id is null and opened_by_name is null and opened_ip is null and opened_client is null))
);

create index ix_secret_shares_creator_created on secret_shares (creator_id, created_at desc);
-- The sweeper's "which ciphertext has outlived its link" scan.
create index ix_secret_shares_waiting_expiry on secret_shares (expires_at) where payload is not null;

alter table app_settings
    add column allow_public_secrets boolean not null default true;
