-- Moderation: account suspension, reversible message removal, an admin audit trail and
-- per-user storage accounting.
--
-- One migration rather than several because these are one feature and they reference each
-- other: the audit trail records bans, and a ban's "clear their messages" action is what
-- soft-delete makes reversible.

-- ---------------------------------------------------------------- accounts ----
-- Suspension is local to this application. Keycloak remains the source of truth for whether
-- an account can authenticate at all; this flag decides whether an authenticated principal is
-- allowed to *use* the chat. Both layers matter: disabling in Keycloak stops new logins but
-- does nothing about a live WebSocket, and this flag stops the session but does not stop them
-- obtaining a fresh token. BanService drives both.
alter table users add column suspended_at    timestamptz;
alter table users add column suspended_by    bigint references users(id);
alter table users add column suspension_note varchar(500);

-- Partial index: the suspended set is expected to stay small, and the admin screen and the
-- per-request enforcement check both filter on "is this one suspended".
create index ix_users_suspended on users(suspended_at) where suspended_at is not null;

-- ---------------------------------------------------------------- messages ----
-- Soft delete. The first ban is sometimes wrong, and "clear everything this account ever
-- wrote" is not an action that should be unrecoverable five seconds after an admin clicks it.
-- Rows stay, disappear from every read path, and a scheduled purge removes them for real
-- after a retention window.
alter table messages add column deleted_at timestamptz;
alter table messages add column deleted_by bigint references users(id);

-- Every message read path filters "not deleted", so the existing (channel_id, created_at)
-- index needs a live-rows-only counterpart to stay useful.
create index ix_messages_channel_live on messages(channel_id, created_at) where deleted_at is null;
-- Drives the purge job and the "how much is pending deletion" admin figure.
create index ix_messages_deleted on messages(deleted_at) where deleted_at is not null;
-- "Everything by this author", the query behind bulk cleanup.
create index ix_messages_author on messages(author_id, created_at);

-- ------------------------------------------------------------------- audit ----
-- Who did what to whom. Append-only by convention: nothing in the application updates or
-- deletes a row here. actor_id is nullable so a system action (the scheduled purge) is
-- distinguishable from an admin action rather than being attributed to whoever happened to
-- deploy last.
create table admin_audit (
    id            bigint       generated by default as identity primary key,
    actor_id      bigint       references users(id),
    action        varchar(64)  not null,
    target_user   bigint       references users(id),
    target_ref    varchar(255),
    detail        varchar(1000),
    created_at    timestamptz  not null default now()
);
create index ix_admin_audit_created on admin_audit(created_at desc);
create index ix_admin_audit_target  on admin_audit(target_user, created_at desc);

-- --------------------------------------------------------------- storage ------
-- Per-user attachment usage, maintained incrementally rather than summed on every upload:
-- the sum over attachments would need a join through messages to the author on a path that is
-- already the throughput-sensitive one.
--
-- This is a quota, not a disk guarantee. The filesystem quota (ZFS dataset, LVM, whatever) is
-- the thing that actually stops the volume filling; this stops one account consuming everyone
-- else's share long before the filesystem notices, and gives the admin screen a number.
create table user_storage (
    user_id      bigint      primary key references users(id) on delete cascade,
    bytes_used   bigint      not null default 0,
    quota_bytes  bigint,
    updated_at   timestamptz not null default now(),
    constraint ck_user_storage_nonneg check (bytes_used >= 0)
);

-- Backfill from what is already on disk so the first quota check is not wrong for existing
-- users. Attachments hang off messages, whose author is the uploader.
insert into user_storage (user_id, bytes_used)
select m.author_id, coalesce(sum(a.size_bytes), 0)
from attachments a
join messages m on m.id = a.message_id
group by m.author_id
on conflict (user_id) do nothing;
